/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IMdiAccount: typeof import('~icons/mdi/account')['default']
    IMdiKey: typeof import('~icons/mdi/key')['default']
    IMdiMessage: typeof import('~icons/mdi/message')['default']
    IMdiPause: typeof import('~icons/mdi/pause')['default']
    IMdiPlay: typeof import('~icons/mdi/play')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
